### ISSUE TITLE
Name of Types

### ISSUE THREAD

**Issue by alecloudenback** [iitis/DatagenCopulaBased.jl#13]
Hello! I am a user/developer trying out this package for use in EconomicScenarioGenerators.jl and have some questions/feedback. Thank you for this package ❤️ 

I think that `GaussianCopula` and `MarshalOlkinCopula` would be more Julian names than `Gaussian_cop` and `Marshal_Olkin_cop`, for example.

https://docs.julialang.org/en/v1/manual/style-guide/#Use-naming-conventions-consistent-with-Julia-base/

**Comment by kdomino** [comment]
Thank you for this comment, I will make corrections next week.

**Comment by kdomino** [comment]
In commit 4f94ae0830e6cc7e2f66ab76d092569737a76817, I renamed copula names. If everything is ok. , I will make a new release

**Comment by kdomino** [comment]
handled in release ```v1.4.0```
