### ISSUE TITLE
help with empirical copulas

### ISSUE THREAD

**Issue by EthanRLeonard** [iitis/DatagenCopulaBased.jl#14]
Hey, kind of new to the whole copula thing. Could you show an example of how to get the empirical copula for a given dataset? 

Any help or advice appreciated. Love how thorough the docs are.

**Comment by kdomino** [comment]
I would transform multivariate data to such with uniform marginals, and then fit multivariate Empirical Cumulative Distribution Function. I am not sure, what particular module you should use for this in Julia. Take a look here: https://juliastats.org/StatsBase.jl/stable/empirical/#StatsBase.ecdf  but such ecdf  may only be supported form uni-variate data.
