### ISSUE TITLE
Improve dispatching

### ISSUE THREAD

**Issue by rcalxrc08** [iitis/DatagenCopulaBased.jl#2]
In order to use your library from outside it would be very nice to have kind of a dispatch functionality.
Currently in order to specify which copula to use you need to call different functions, this is not so useful when you want to write generic code on top of your library (my case XD).

It would be nice to select the kind of copula though a struct/type which carries as well the copula parameters, and then a generic simulate_copula method which will dispatch to the correct copula.

I was going to implement this from outside but probably it's better if done already in the library.

Just to give you a proper example:
Current:
`Corr=[1.0 0.0;0.0 1.0];`
`U_joint=gausscopulagen(Nsim,Corr);`
Proposal:
`copula_=GaussianCopula([1.0 0.0;0.0 1.0]);`
`U_joint=simulate_copula(Nsim,copula_);`

**Comment by kdomino** [comment]
Acknowledged, I put the issues into the queue of my tasks

**Comment by kdomino** [comment]
will be done in version 1.1

**Comment by kdomino** [comment]
done in version 1.1
