### ISSUE TITLE
methods with preallocated output

### ISSUE THREAD

**Issue by rcalxrc08** [iitis/DatagenCopulaBased.jl#5]
Hi again,

Following the examples from the base Random library, it would be nice to have a simulate_copula! function where the first argument is the output Matrix instead of the integer representing the number of simulations. This will lead to a great performance improvement (IMHO).

**Comment by kdomino** [comment]
Will be done in version 1.3. The samplers have been prepared already.

**Comment by kdomino** [comment]
Commited simulate_copula!(u, cop) supported for all Archimedean copulas (including nested and the chain) as well as the Frechet and the Marshall-Olkin ones

**Comment by kdomino** [comment]
Issued version 1.3 with mentioned above functionalities
