### ISSUE TITLE
possible test failure in upcoming Julia version 1.5 

### ISSUE THREAD

**Issue by rfourquet** [iitis/DatagenCopulaBased.jl#6]
A PkgEval run for a Julia [pull request](https://github.com/JuliaLang/julia/pull/29240) which changes the generated numbers for `rand(a:b)` indicates that the tests of this package might fail in Julia 1.5 (and on Julia current master branch).

Also, you might be interested in using the new [StableRNGs.jl](https://github.com/rfourquet/StableRNGs.jl) registered package, which provides guaranteed stable streams of random numbers across Julia releases.

Apologies if this is a false positive. Cf. https://github.com/JuliaCI/NanosoldierReports/blob/ab6676206b210325500b4f4619fa711f2d7429d2/pkgeval/by_hash/52c2272_vs_47c55db/logs/DatagenCopulaBased/1.5.0-DEV-87d2a04de3.log

**Comment by kdomino** [comment]
Corrected on Linux,  StableRNGs.jl used in some tests

On osx on - nightly problem with:

Building TimeZones → `~/.julia/packages/TimeZones/X323b/deps/build.log`
Error: Error building `TimeZones`: 
ERROR: LoadError: LoadError: LoadError: InexactError: check_top_bit(Int32, 4294967248)

**Comment by rfourquet** [comment]
> On osx on - nightly problem with:

I have seen a similar problem reported somewhere else, e.g. https://github.com/JuliaData/DataFrames.jl/pull/2223#issuecomment-623603387, which seems to be a current problem with Julia nightly.

**Comment by kdomino** [comment]
Ok thank you. I will wait for the problem to be fixed.

**Comment by kdomino** [comment]
Resolved
